import XCTest

final class CurveBackdropTests: XCTestCase {
    /// The committed fixture, generated by `cargo test -p pe-session --test fixtures`.
    private func fixture() throws -> [String: Any] {
        let url = try XCTUnwrap(
            Bundle(for: Self.self).url(forResource: "backdrop_samples", withExtension: "json"),
            "backdrop_samples.json is not in the test bundle"
        )
        return try XCTUnwrap(
            JSONSerialization.jsonObject(with: Data(contentsOf: url)) as? [String: Any]
        )
    }

    /// The engine writes Rust's `Debug` spelling. This is the only place the
    /// two vocabularies meet, spelled out rather than derived from the text, so
    /// a case renamed on either side fails here instead of quietly matching.
    private func backdrop(named name: String) -> CurveBackdrop? {
        switch name {
        case "Tones": .tones
        case "Luma": .luma
        case "Hue": .hue
        case "Saturation": .saturation
        case "Nothing": .nothing
        default: nil
        }
    }

    /// The test this file exists for.
    ///
    /// Swift smooths the histogram itself so a drag costs no round trip per
    /// frame. Two hand-written copies of a seven-tap filter agree until the day
    /// one of them is tidied — and a trace that disagrees with the engine draws
    /// the picture's tones in the wrong place behind the curve acting on them.
    func testTheTraceMatchesTheEngineAtEveryBin() throws {
        let f = try fixture()
        let bins = try XCTUnwrap(f["bins"] as? [Int]).map { UInt32($0) }
        let peak = try XCTUnwrap(f["peak"] as? Double)
        let expected = try XCTUnwrap(f["traced"] as? [Double])
        let got = CurveBackdrop.trace(bins, peak: peak)
        XCTAssertEqual(got.count, expected.count)
        for (i, want) in expected.enumerated() {
            XCTAssertEqual(got[i], want, accuracy: 0.0005, "bin \(i)")
        }
    }

    func testTheLogWindowMatchesTheEngine() throws {
        let w = try XCTUnwrap(try fixture()["window"] as? [String: Double])
        XCTAssertEqual(CurveBackdrop.logBlack, try XCTUnwrap(w["black"]), accuracy: 0.000001)
        XCTAssertEqual(CurveBackdrop.logWhite, try XCTUnwrap(w["white"]), accuracy: 0.000001)
    }

    func testEveryCurveGetsTheBackdropTheEngineSays() throws {
        let behind = try XCTUnwrap(try fixture()["behind"] as? [String: String])
        XCTAssertFalse(behind.isEmpty, "the fixture named no curves at all")
        for (key, want) in behind {
            XCTAssertEqual(
                CurveBackdrop.behind(key), try XCTUnwrap(backdrop(named: want), want), "\(key)"
            )
        }
        // The one that was wrong, named so a regression says what it is.
        XCTAssertEqual(CurveBackdrop.behind("lum_vs_sat"), .luma)
    }

    func testACurveNobodyKnowsAboutGetsNothing() {
        // Drawing nothing is the right answer for an unknown axis. A plausible
        // count of the wrong quantity would be the worse of the two.
        XCTAssertEqual(CurveBackdrop.behind("not_a_curve"), .nothing)
    }

    /// A tone plot spans black to diffuse white, not the whole log domain. Laid
    /// out edge to edge instead, every tone sits about a seventh of the plot to
    /// the left of where the curve acts on it.
    func testATonePlotReadsItsBinsThroughTheSdrWindow() {
        // The left edge of the plot is diffuse black, not bin zero.
        XCTAssertEqual(
            CurveBackdrop.bin(atPlotFraction: 0),
            Int((CurveBackdrop.logBlack * 255).rounded())
        )
        XCTAssertEqual(
            CurveBackdrop.bin(atPlotFraction: 1),
            Int((CurveBackdrop.logWhite * 255).rounded())
        )
        // And it is a window, not the whole thing.
        XCTAssertGreaterThan(CurveBackdrop.bin(atPlotFraction: 0), 0)
        XCTAssertLessThan(CurveBackdrop.bin(atPlotFraction: 1), 255)
    }

    func testASecondaryPlotReadsItsBinsEdgeToEdge() {
        // A hue runs once round the circle and a saturation runs zero to one:
        // both fill their plot, so neither is windowed.
        XCTAssertEqual(CurveBackdrop.spreadBin(atPlotFraction: 0), 0)
        XCTAssertEqual(CurveBackdrop.spreadBin(atPlotFraction: 1), 255)
    }
}
