import XCTest

final class CurveGeometryTests: XCTestCase {
    /// The committed fixture, generated by `cargo test -p pe-session --test fixtures`.
    private func samples() throws -> [String: (points: [CGPoint], samples: [Double])] {
        let url = try XCTUnwrap(
            Bundle(for: Self.self).url(forResource: "curve_samples", withExtension: "json"),
            "curve_samples.json is not in the test bundle"
        )
        let raw = try JSONSerialization.jsonObject(with: Data(contentsOf: url)) as? [String: Any]
        var out: [String: (points: [CGPoint], samples: [Double])] = [:]
        for (name, value) in try XCTUnwrap(raw) {
            let entry = try XCTUnwrap(value as? [String: Any])
            let pairs = try XCTUnwrap(entry["points"] as? [[Double]])
            let s = try XCTUnwrap(entry["samples"] as? [Double])
            out[name] = (pairs.map { CGPoint(x: $0[0], y: $0[1]) }, s)
        }
        return out
    }

    /// The test this file exists for.
    ///
    /// Swift reimplements the engine's interpolation so the editor can draw a
    /// preview without a round trip per frame. If the two ever disagree, the
    /// line being dragged is not the line that renders — and the disagreement
    /// is largest exactly where the user is paying attention.
    func testEveryCurveMatchesTheEngineAtEveryLutPosition() throws {
        for (name, entry) in try samples() {
            let curve = CurveGeometry(points: entry.points)
            for (i, expected) in entry.samples.enumerated() {
                let x = Double(i) / 255.0
                let got = curve.sample(at: x)
                XCTAssertEqual(
                    got, expected, accuracy: 0.0005,
                    "\(name) diverged at x = \(x): Swift \(got), engine \(expected)"
                )
            }
        }
    }

    func testAMonotoneCurveDoesNotOvershootItsControlPoints() {
        // The property the engine chose Fritsch-Carlson for. Catmull-Rom would
        // bulge above the highest point somewhere in the middle, which on a
        // tone curve is a bright halo in a band nobody touched.
        let curve = CurveGeometry(points: [
            CGPoint(x: 0, y: 0), CGPoint(x: 0.7, y: 0.95),
            CGPoint(x: 0.85, y: 0.97), CGPoint(x: 1, y: 0.5),
        ])
        for i in 0...255 {
            let y = curve.sample(at: Double(i) / 255.0)
            XCTAssertLessThanOrEqual(y, 0.97 + 0.0005, "overshot at \(i)")
        }
    }

    func testOutsideTheControlRangeTheCurveHoldsItsEndpoint() {
        let curve = CurveGeometry(points: [CGPoint(x: 0.2, y: 0.3), CGPoint(x: 0.8, y: 0.7)])
        XCTAssertEqual(curve.sample(at: 0), 0.3, accuracy: 0.0005)
        XCTAssertEqual(curve.sample(at: 0.1), 0.3, accuracy: 0.0005)
        XCTAssertEqual(curve.sample(at: 0.9), 0.7, accuracy: 0.0005)
        XCTAssertEqual(curve.sample(at: 1), 0.7, accuracy: 0.0005)
    }

    func testFewerThanTwoPointsIsTheIdentity() {
        // Matching the engine, which falls back to `x` rather than failing.
        XCTAssertEqual(CurveGeometry(points: []).sample(at: 0.42), 0.42, accuracy: 0.0005)
        XCTAssertEqual(
            CurveGeometry(points: [CGPoint(x: 0.5, y: 0.9)]).sample(at: 0.42),
            0.42, accuracy: 0.0005
        )
    }

    func testAddingAPointKeepsThePointsInOrder() {
        // A curve is evaluated in x order; inserting out of order and relying
        // on a later sort is how a drag past a neighbour produces a curve that
        // doubles back.
        var curve = CurveGeometry(points: [CGPoint(x: 0, y: 0), CGPoint(x: 1, y: 1)])
        curve = curve.adding(CGPoint(x: 0.5, y: 0.8))
        XCTAssertEqual(curve.points.map(\.x), [0, 0.5, 1])
    }

    func testThePointNearestATapIsFoundOnlyWithinReach() {
        let curve = CurveGeometry(points: [
            CGPoint(x: 0, y: 0), CGPoint(x: 0.5, y: 0.5), CGPoint(x: 1, y: 1),
        ])
        XCTAssertEqual(curve.indexOfPoint(near: CGPoint(x: 0.52, y: 0.48), within: 0.05), 1)
        XCTAssertNil(curve.indexOfPoint(near: CGPoint(x: 0.2, y: 0.9), within: 0.05))
    }

    func testAnEndpointCannotBeRemoved() {
        // Removing an end would let the curve stop short of the range it is
        // evaluated over, and the engine holds the endpoint value across the
        // gap — so the user would see a flat shelf they did not ask for.
        let curve = CurveGeometry(points: [
            CGPoint(x: 0, y: 0), CGPoint(x: 0.5, y: 0.5), CGPoint(x: 1, y: 1),
        ])
        XCTAssertFalse(curve.canRemovePoint(at: 0))
        XCTAssertTrue(curve.canRemovePoint(at: 1))
        XCTAssertFalse(curve.canRemovePoint(at: 2))
        XCTAssertEqual(curve.removing(at: 1).points.count, 2)
        XCTAssertEqual(curve.removing(at: 0).points.count, 3, "an endpoint went away")
    }

    func testDraggingAPointIsClampedToTheUnitSquareAndItsNeighbours() {
        // A point dragged past a neighbour would make x non-monotone, which the
        // evaluator resolves by sorting — so the point the user is holding
        // would swap places with another mid-drag.
        let curve = CurveGeometry(points: [
            CGPoint(x: 0, y: 0), CGPoint(x: 0.5, y: 0.5), CGPoint(x: 1, y: 1),
        ])
        let far = curve.moving(at: 1, to: CGPoint(x: 5, y: 5))
        XCTAssertLessThan(far.points[1].x, 1)
        XCTAssertLessThanOrEqual(far.points[1].y, 1)

        let back = curve.moving(at: 1, to: CGPoint(x: -3, y: -3))
        XCTAssertGreaterThan(back.points[1].x, 0)
        XCTAssertGreaterThanOrEqual(back.points[1].y, 0)
    }

    func testAnEndpointKeepsItsXWhenDragged() {
        // The ends anchor the range. Letting them slide inward would shorten
        // the curve and produce the same shelf as removing one.
        let curve = CurveGeometry(points: [CGPoint(x: 0, y: 0), CGPoint(x: 1, y: 1)])
        let moved = curve.moving(at: 0, to: CGPoint(x: 0.4, y: 0.6))
        XCTAssertEqual(moved.points[0].x, 0, accuracy: 0.0001)
        XCTAssertEqual(moved.points[0].y, 0.6, accuracy: 0.0001)
    }
}
