import CoreGraphics
import SwiftUI
import XCTest

/// The spectral locus on this side, and the field the pins plot is drawn on.
///
/// Two halves. The first holds `Locus` to `locus.json` — the engine's own
/// answers, written by `cargo test -p pe-session --test fixtures` — the way
/// `CurveGeometryTests`, `WarpGeometryTests` and `PinGeometryTests` hold
/// theirs. It asserts **exact** equality rather than a tolerance, which the
/// arithmetic allows because the mirror is `Float` doing the same operations in
/// the same order on the same values as the engine's `f32`. A tolerance would
/// pass a Swift copy that had drifted a texel's worth in every colour on the
/// plot, and that drift is exactly what a second implementation does.
///
/// The second half renders the editor and reads the pixels back, because this
/// machine cannot look at the screen. What that catches is a field in the
/// wrong *place* or the wrong way up — a mirrored chromaticity diagram is
/// still a beautiful spread of colour and is confidently wrong.
final class LocusTests: XCTestCase {

    // ---- the fixture ------------------------------------------------------

    /// The committed fixture, generated by `cargo test -p pe-session --test fixtures`.
    private func fixture() throws -> [String: Any] {
        let url = try XCTUnwrap(
            Bundle(for: Self.self).url(forResource: "locus", withExtension: "json"),
            "locus.json is not in the test bundle"
        )
        return try XCTUnwrap(
            JSONSerialization.jsonObject(with: Data(contentsOf: url)) as? [String: Any])
    }

    private struct Probe {
        let name: String
        let xy: SIMD2<Float>
        let inside: Bool
        let colour: SIMD3<Float>?
    }

    private func probes() throws -> [Probe] {
        let raw = try XCTUnwrap(try fixture()["probes"] as? [[String: Any]])
        return try raw.map { entry in
            let xy = try XCTUnwrap(entry["xy"] as? [Double])
            let colour = entry["colour"] as? [Double]
            return Probe(
                name: try XCTUnwrap(entry["name"] as? String),
                xy: SIMD2(Float(xy[0]), Float(xy[1])),
                inside: try XCTUnwrap(entry["inside"] as? Bool),
                colour: colour.map { SIMD3(Float($0[0]), Float($0[1]), Float($0[2])) }
            )
        }
    }

    /// The table itself, which everything else on this plot is derived from.
    func testEveryTabulatedPointIsTheEngines() throws {
        let want = try XCTUnwrap(try fixture()["locus"] as? [[Double]])
        XCTAssertEqual(Locus.table.count, want.count, "the table is a different length")
        for (i, p) in want.enumerated() {
            XCTAssertEqual(Locus.table[i].x, Float(p[0]), "point \(i) x")
            XCTAssertEqual(Locus.table[i].y, Float(p[1]), "point \(i) y")
        }
        XCTAssertEqual(
            try XCTUnwrap(try fixture()["subdivisions"] as? Int), Locus.subdivisions,
            "the curve is subdivided a different number of times")
    }

    /// Every drawn point, not a subsample of them.
    ///
    /// The fixture holds all 513 for a reason the plan states: a copy that
    /// subdivided fifteen times instead of sixteen, or that rounded the line of
    /// purples off with the rest of the spline, would still pass a check that
    /// only looked at the tabulated points the spline interpolates *between*.
    func testEveryDrawnPointIsTheEngines() throws {
        let want = try XCTUnwrap(try fixture()["curve"] as? [[Double]])
        XCTAssertEqual(
            Locus.curve.count, want.count,
            "the curve is \(Locus.curve.count) points and the engine draws \(want.count)")
        for (i, p) in want.enumerated() {
            XCTAssertEqual(Locus.curve[i].x, Float(p[0]), "curve point \(i) x")
            XCTAssertEqual(Locus.curve[i].y, Float(p[1]), "curve point \(i) y")
        }
    }

    /// Which chromaticities are colours at all — the answer the field dims by.
    func testEveryProbeIsInsideOrOutsideTheWayTheEngineSaysItIs() throws {
        for probe in try probes() {
            XCTAssertEqual(
                Locus.inside(probe.xy.x, probe.xy.y), probe.inside,
                "\(probe.name) at \(probe.xy)")
        }
    }

    /// And what is drawn there, exactly.
    ///
    /// Including outside the horseshoe, where the engine still answers: a copy
    /// that drew black out there would give the plot a surround instead of a
    /// continuous field, which is the one thing this whole drawing is about.
    func testEveryProbeIsTheColourTheEngineDraws() throws {
        for probe in try probes() {
            let got = Locus.colour(at: probe.xy)
            guard let want = probe.colour else {
                XCTAssertNil(got, "\(probe.name) has no colour and this drew \(String(describing: got))")
                continue
            }
            let drawn = try XCTUnwrap(got, "\(probe.name) had nothing to draw")
            XCTAssertEqual(drawn.x, want.x, "\(probe.name) red")
            XCTAssertEqual(drawn.y, want.y, "\(probe.name) green")
            XCTAssertEqual(drawn.z, want.z, "\(probe.name) blue")
        }
    }

    // ---- the image ---------------------------------------------------------

    /// The dimming, read off the image itself.
    ///
    /// `Locus.colour(at:)` normalises every colour to full brightness, so the
    /// brightest channel of every texel is the dim it was multiplied by and
    /// nothing else: 158 for a colour, 40 for one that no eye can see, and 8
    /// along the sliver below y = 0 where there is no colour to normalise.
    /// Three populations, all three present, and none of them zero — that last
    /// is the whole argument for dimming rather than blackening.
    func testEveryTexelIsDimmedByItsOwnSideOfTheHorseshoe() throws {
        let image = try XCTUnwrap(Locus.field, "the field was not built")
        let provider = try XCTUnwrap(image.dataProvider, "the field has no bytes")
        let data = [UInt8](try XCTUnwrap(provider.data) as Data)
        let bright = UInt8(Locus.insideLevel * 255)
        let dim = UInt8(Locus.outsideLevel * 255)
        let nothing = UInt8(Locus.nothingAtAll.max() * 255)
        var tally: [UInt8: Int] = [:]
        for i in stride(from: 0, to: data.count, by: 4) {
            let peak = Swift.max(data[i], Swift.max(data[i + 1], data[i + 2]))
            tally[peak, default: 0] += 1
            XCTAssertEqual(data[i + 3], 255, "the field is the plot's ground and has to be opaque")
        }
        XCTAssertEqual(
            Set(tally.keys), [bright, dim, nothing],
            "the field is dimmed to \(tally.keys.sorted()) and not to "
                + "\(bright) inside, \(dim) outside and \(nothing) where there is no colour")
        XCTAssertGreaterThan(tally[bright] ?? 0, 5000, "almost nothing is drawn as a real colour")
        XCTAssertGreaterThan(tally[dim] ?? 0, 5000, "almost nothing is drawn as dimmed")
        XCTAssertLessThan(dim, bright, "outside the horseshoe is not the dimmer of the two")
        // The whole argument, and the one part of it a set of three numbers
        // cannot make on its own: what is outside is *dimmed*. At zero the
        // three populations above are still three distinct numbers and every
        // assertion so far still holds, and the plot is a shape floating in
        // nothing.
        XCTAssertGreaterThan(dim, 0, "outside the horseshoe was blackened rather than dimmed")
        XCTAssertGreaterThan(
            nothing, 0, "the strip below y = 0 was blackened rather than left near-black")
    }

    // ---- what a render can show -------------------------------------------

    /// A chromaticity inside the horseshoe is drawn brighter than one outside.
    ///
    /// Read either side of the line of purples at the same x, where the colour
    /// barely changes and the *dimming* is nearly the whole difference — so
    /// this fails on a field that forgot to dim, and cannot pass by accident on
    /// one that happens to be brighter in the middle.
    @MainActor
    func testAColourInsideTheHorseshoeIsBrighterThanOneOutside() throws {
        let (data, plot, width) = try Self.renderedPlot()
        let g = PinGeometry(pins: [], rect: plot)

        let inside = CGPoint(x: 0.45, y: 0.22)
        let outside = CGPoint(x: 0.45, y: 0.09)
        XCTAssertTrue(Locus.inside(0.45, 0.22), "the test's own inside point is not a colour")
        XCTAssertFalse(Locus.inside(0.45, 0.09), "the test's own outside point is a colour")

        let bright = Self.pixel(data, at: g.screen(of: inside), width: width)
        let dim = Self.pixel(data, at: g.screen(of: outside), width: width)
        // Both are a magenta whose red channel is the normalised peak, so the
        // ratio between them is the ratio of the two dims and nothing else.
        XCTAssertGreaterThan(
            Int(bright.r), Int(dim.r) * 2,
            "inside the horseshoe drew \(bright) and outside drew \(dim)")
        XCTAssertGreaterThan(
            Int(dim.r), 8,
            "outside the horseshoe was blackened rather than dimmed: \(dim)")
    }

    /// The greenest corner is green, and the other two are their own colours.
    ///
    /// Three points that no two orientations of this diagram agree about. A
    /// field drawn upside down, mirrored, or transposed puts a different one of
    /// these three at each of these places, and every one of those is a
    /// perfectly pretty spread of colour.
    @MainActor
    func testTheGreenestCornerIsGreenAndTheRedAndBlueEndsAreTheirOwn() throws {
        let (data, plot, width) = try Self.renderedPlot()
        let g = PinGeometry(pins: [], rect: plot)

        // 520 nm, a hair inside its own vertex — the greenest colour there is.
        let green = Self.pixel(data, at: g.screen(of: CGPoint(x: 0.0794, y: 0.8187)), width: width)
        XCTAssertGreaterThan(Int(green.g), Int(green.r) + 60, "the greenest corner drew \(green)")
        XCTAssertGreaterThan(Int(green.g), Int(green.b) + 60, "the greenest corner drew \(green)")

        // Well up the red end of the locus, clear of the gridlines.
        let red = Self.pixel(data, at: g.screen(of: CGPoint(x: 0.60, y: 0.33)), width: width)
        XCTAssertGreaterThan(Int(red.r), Int(red.g) + 60, "the red end drew \(red)")
        XCTAssertGreaterThan(Int(red.r), Int(red.b) + 60, "the red end drew \(red)")

        // The sRGB blue primary, down in the corner the purples run to.
        let blue = Self.pixel(data, at: g.screen(of: CGPoint(x: 0.15, y: 0.06)), width: width)
        XCTAssertGreaterThan(Int(blue.b), Int(blue.r) + 60, "the blue end drew \(blue)")
        XCTAssertGreaterThan(Int(blue.b), Int(blue.g) + 60, "the blue end drew \(blue)")
    }

    /// The plot is a field and not a fill.
    ///
    /// Counted rather than sampled: a plot painted one colour, or left as the
    /// `WELL` it used to be, has a handful of distinct pixels in it and this
    /// one has about twelve and a half thousand. The floor is set well under
    /// that and well over what a *coarse* field manages — building the same
    /// picture from chromaticities rounded to a tenth gets to 1,924, and that
    /// is the thing this is really looking for, since a plot with no gradient
    /// in it at all is already caught by the two unlike corners above.
    @MainActor
    func testThePlotIsAFieldOfColourAndNotOneColour() throws {
        let (data, plot, width) = try Self.renderedPlot()
        var seen = Set<UInt32>()
        for y in Int(plot.minY)..<Int(plot.maxY) {
            for x in Int(plot.minX)..<Int(plot.maxX) {
                let p = Self.pixel(data, x: x, y: y, width: width)
                seen.insert(
                    UInt32(p.r) << 16 | UInt32(p.g) << 8 | UInt32(p.b))
            }
        }
        XCTAssertGreaterThan(
            seen.count, 2000,
            "the plot has \(seen.count) distinct colours in it, which is not a field")
    }

    /// The boundary is stroked over the field.
    ///
    /// Looked for on the line of purples, where the field either side is a
    /// magenta with **no green in it at all** — so any green found there is the
    /// white stroke and cannot be the field showing through.
    @MainActor
    func testTheHorseshoeIsStrokedOverTheField() throws {
        let (data, plot, width) = try Self.renderedPlot()
        let g = PinGeometry(pins: [], rect: plot)

        // Where the chord from 380 nm to 700 nm sits at x = 0.45, from the
        // table itself rather than from a number written down here.
        let a = Locus.table[0], b = Locus.table[Locus.table.count - 1]
        let t = (0.45 - a.x) / (b.x - a.x)
        let at = g.screen(of: CGPoint(x: 0.45, y: Double(a.y + t * (b.y - a.y))))

        // Antialiasing puts the stroke within a pixel of where it was asked
        // for, so the line is the brightest green in a small window and the
        // field is what is left ten pixels away.
        var onTheLine = 0
        for dy in -2...2 {
            let p = Self.pixel(data, x: Int(at.x), y: Int(at.y) + dy, width: width)
            onTheLine = Swift.max(onTheLine, Int(p.g))
        }
        let above = Self.pixel(data, x: Int(at.x), y: Int(at.y) - 10, width: width)
        let below = Self.pixel(data, x: Int(at.x), y: Int(at.y) + 10, width: width)
        XCTAssertLessThan(Int(above.g), 12, "the field itself has green in it here: \(above)")
        XCTAssertLessThan(Int(below.g), 12, "the field itself has green in it here: \(below)")
        XCTAssertGreaterThan(
            onTheLine, 30,
            "nothing was stroked along the line of purples: \(onTheLine) against "
                + "\(above.g) above and \(below.g) below")
    }

    // ---- rendering ---------------------------------------------------------

    /// The editor, rendered, with the plot's own square found in it.
    ///
    /// No measurement is asked for, so no cloud is drawn: what is in the square
    /// is the field, the boundary, the gridlines and the white point.
    @MainActor
    private static func renderedPlot() throws -> (data: [UInt8], plot: CGRect, width: Int) {
        let store = try XCTUnwrap(SessionStore())
        // The width the inspector actually gives it. Rendered narrower, the
        // five `ScalarRow`s below the plot cannot fit their own label, readout
        // and reset arrow, and the plot is squeezed to nothing.
        let width = Int(RowMetrics.minimumPanel - RowMetrics.inset * 2)
        let json = #"{"key": "pins", "name": "Pins", "kind": "pins"}"#
        let param = try JSONDecoder().decode(Param.self, from: Data(json.utf8))
        let view = PinsEditor(
            param: param, row: 0, value: [], isActive: true, store: store)
        let renderer = ImageRenderer(content: view.frame(width: CGFloat(width), height: 620))
        renderer.scale = 1
        let image = try XCTUnwrap(renderer.cgImage, "the renderer produced no image")
        let data = bytes(image)
        XCTAssertNil(store.scopes, "something measured a frame and drew a cloud over the field")

        // The plot is the first thing in the stack and the field fills it edge
        // to edge, so it is the opaque square at the top: the first row with
        // any ink in it at all, and as tall as it is wide.
        var top = 0
        while top < image.height,
            !(0..<width).contains(where: { pixel(data, x: $0, y: top, width: width).a > 0 })
        { top += 1 }
        XCTAssertLessThan(top, image.height, "nothing was drawn at all")

        // Checked rather than assumed — a rect guessed a quarter too narrow
        // reads every position off by that much, which is these tests' own
        // version of the bug they are looking for. Both of the plot's top
        // corners are opaque, and they are two *different* colours, which is
        // what the field made of the flat `WELL` that used to be there.
        let left = pixel(data, x: 6, y: top + 6, width: width)
        let right = pixel(data, x: width - 7, y: top + 6, width: width)
        XCTAssertGreaterThan(left.a, 250, "the plot's top-left corner is not opaque")
        XCTAssertGreaterThan(right.a, 250, "the plot's top-right corner is not opaque")
        XCTAssertGreaterThan(
            abs(Int(left.r) - Int(right.r)) + abs(Int(left.b) - Int(right.b)), 30,
            "the plot's two top corners drew \(left) and \(right), which is a fill and not a field")
        XCTAssertEqual(
            pixel(data, x: 6, y: top + width + 3, width: width).a, 0,
            "the square found is taller than it is wide")
        return (data, CGRect(x: 0, y: top, width: width, height: width), width)
    }

    private struct Pixel: Equatable, CustomStringConvertible {
        let r: UInt8, g: UInt8, b: UInt8, a: UInt8
        var description: String { "(\(r), \(g), \(b), \(a))" }
    }

    private static func bytes(_ image: CGImage) -> [UInt8] {
        let (w, h) = (image.width, image.height)
        var bytes = [UInt8](repeating: 0, count: w * h * 4)
        guard
            let context = CGContext(
                data: &bytes, width: w, height: h, bitsPerComponent: 8, bytesPerRow: w * 4,
                space: CGColorSpaceCreateDeviceRGB(),
                bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue)
        else { return bytes }
        context.draw(image, in: CGRect(x: 0, y: 0, width: w, height: h))
        return bytes
    }

    private static func pixel(_ bytes: [UInt8], x: Int, y: Int, width: Int) -> Pixel {
        let i = (y * width + x) * 4
        guard x >= 0, x < width, y >= 0, i >= 0, i + 3 < bytes.count else {
            return Pixel(r: 0, g: 0, b: 0, a: 0)
        }
        return Pixel(r: bytes[i], g: bytes[i + 1], b: bytes[i + 2], a: bytes[i + 3])
    }

    private static func pixel(_ bytes: [UInt8], at p: CGPoint, width: Int) -> Pixel {
        pixel(bytes, x: Int(p.x), y: Int(p.y), width: width)
    }
}
