import XCTest

/// What holds the two shells to one scheme.
///
/// `theme.json` is generated by `crates/pe-session/tests/fixtures.rs` from
/// `pe_theme`, which is also what the Windows shell draws from. Every
/// assertion here is exact — a colour is three bytes and either it is the same
/// three bytes or the two applications are different colours.
final class PaletteTests: XCTestCase {
    private func fixture() throws -> [String: Any] {
        let url = try XCTUnwrap(
            Bundle(for: Self.self).url(forResource: "theme", withExtension: "json"),
            "theme.json is not in the test bundle"
        )
        return try XCTUnwrap(
            JSONSerialization.jsonObject(with: Data(contentsOf: url)) as? [String: Any]
        )
    }

    /// Every colour in the application comes from one place, and that place is
    /// shared with the Windows shell. A palette that drifts is how a viewer
    /// surround, a filmstrip and a status bar become three shades of one grey.
    func testEveryPaletteEntryMatchesTheEngine() throws {
        let palette = try XCTUnwrap(fixture()["palette"] as? [String: String])
        XCTAssertFalse(palette.isEmpty, "the fixture carries no palette")
        for (name, hex) in palette {
            let colour = try XCTUnwrap(
                Palette.named(name), "Swift has no colour called \(name)")
            XCTAssertEqual(
                Palette.hex(colour), hex,
                "\(name) is \(Palette.hex(colour)) here and \(hex) in the engine")
        }
    }

    /// And nothing extra, which is the half that catches a colour invented on
    /// the Swift side and then quietly used in three places.
    func testSwiftHasNoColoursTheEngineDoesNot() throws {
        let palette = try XCTUnwrap(fixture()["palette"] as? [String: String])
        XCTAssertEqual(
            Set(Palette.allNames), Set(palette.keys),
            "the two palettes name different colours")
    }

    func testEveryRampChoiceMatchesTheEngine() throws {
        let ramps = try XCTUnwrap(fixture()["ramps"] as? [String: String])
        XCTAssertFalse(ramps.isEmpty, "the fixture carries no ramp assignments")
        for (path, want) in ramps {
            let parts = path.split(separator: ".", maxSplits: 1)
            let got = Ramp.for(effect: String(parts[0]), key: String(parts[1]))
            XCTAssertEqual(got.tag, want, path)
        }
    }

    func testEveryRampPaintsWhatTheEngineWouldPaint() throws {
        let sampled = try XCTUnwrap(fixture()["sampled"] as? [String: [String]])
        XCTAssertFalse(sampled.isEmpty, "the fixture carries no sampled ramps")
        for (name, steps) in sampled {
            let ramp = try XCTUnwrap(Ramp.named(name), "no Swift ramp called \(name)")
            for (i, want) in steps.enumerated() {
                let got = Palette.hex(ramp.at(Double(i) / 16))
                XCTAssertEqual(got, want, "\(name) at step \(i)")
            }
        }
    }

    /// The wheel's three sliders reach their ramps as a constant rather than
    /// through `Ramp.for`, so nothing above would notice if this side's copy of
    /// them said something else.
    func testTheWheelAxesMatchTheEngine() throws {
        let axes = try XCTUnwrap(fixture()["axes"] as? [String])
        XCTAssertEqual(Ramp.channelAxes.map(\.tag), axes)
    }

    /// A spelling only holds two languages together if it reads back as what
    /// was written. `hueAround(28)` that parses to 2.8 would pass every test
    /// above and paint the wrong band.
    func testARampSpellingReadsBackAsWhatItSpelled() {
        for ramp in [
            Ramp.plain, .temp, .tint, .hue, .chroma, .luma,
            .hueAround(0), .hueAround(28), .hueAround(312),
            .sat(Rgb8(35, 228, 235)),
            .axis(Rgb8(72, 200, 208), Rgb8(226, 78, 72)),
        ] {
            XCTAssertEqual(Ramp.named(ramp.tag), ramp, ramp.tag)
        }
    }

    /// And a spelling nobody defined is not a ramp, rather than the nearest
    /// one — the fixture naming something this side has never heard of has to
    /// fail loudly.
    func testAnUnknownSpellingIsNotARamp() {
        for tag in ["", "Temp", "sat", "sat(1,2)", "sat(1,2,3,4)", "hueAround()", "beige"] {
            XCTAssertNil(Ramp.named(tag), tag)
        }
    }

    /// The hue circle closes, here as in the engine. A Hue track that did not
    /// come back to red would be the broken one.
    func testTheHueRampComesBackRound() {
        XCTAssertEqual(Ramp.hue.at(0), Ramp.hue.at(1))
        XCTAssertNotEqual(Ramp.hue.at(0), Ramp.hue.at(0.5))
    }

    /// Every ramp is defined across its whole span and clamps outside it.
    func testEveryRampClampsOutsideItsSpan() {
        for ramp in [
            Ramp.plain, .temp, .tint, .hue, .chroma, .luma,
            .hueAround(120),
            .sat(Rgb8(200, 80, 80)),
            .axis(Rgb8(0, 200, 200), Rgb8(200, 0, 0)),
        ] {
            XCTAssertEqual(ramp.at(-1), ramp.at(0), "\(ramp.tag) does not clamp low")
            XCTAssertEqual(ramp.at(2), ramp.at(1), "\(ramp.tag) does not clamp high")
        }
    }

    /// A plain track is the palette's track colour and not a grey of its own.
    func testAPlainTrackIsThePalettesTrack() {
        XCTAssertEqual(Ramp.plain.at(0.5), Palette.track.rgb)
        XCTAssertTrue(Ramp.plain.isPlain)
        XCTAssertFalse(Ramp.temp.isPlain)
    }

    /// A parameter that merely looks like a colour control keeps a plain
    /// track. Every one of these read as white balance or hue under a
    /// `contains` test.
    func testParametersThatMerelyLookLikeColourControlsStayPlain() {
        for (effect, key) in [
            ("film_damage", "tilt_amount"),
            ("tone", "highlights"),
            ("grain", "shadow_gain"),
            ("colour_mixer", "beige_hue"),
            ("dehaze", "display_depth"),
        ] {
            XCTAssertTrue(
                Ramp.for(effect: effect, key: key).isPlain,
                "\(effect).\(key) was given a gradient it has no business with")
        }
    }
}
