import XCTest

final class WarpGeometryTests: XCTestCase {
    private func plot() -> CGRect {
        CGRect(x: 0, y: 0, width: 200, height: 200)
    }

    /// The committed fixture, generated by `cargo test -p pe-session --test fixtures`.
    private func fixtureHomes() throws -> [String: (cols: Int, rows: Int, wrap: Bool, homes: [CGPoint])] {
        let url = try XCTUnwrap(
            Bundle(for: Self.self).url(forResource: "warp_samples", withExtension: "json"),
            "warp_samples.json is not in the test bundle"
        )
        let raw = try JSONSerialization.jsonObject(with: Data(contentsOf: url)) as? [String: Any]
        let homes = try XCTUnwrap(try XCTUnwrap(raw)["homes"] as? [String: Any])
        var out: [String: (cols: Int, rows: Int, wrap: Bool, homes: [CGPoint])] = [:]
        for (name, value) in homes {
            let e = try XCTUnwrap(value as? [String: Any])
            let pairs = try XCTUnwrap(e["homes"] as? [[Double]])
            out[name] = (
                try XCTUnwrap(e["cols"] as? Int),
                try XCTUnwrap(e["rows"] as? Int),
                try XCTUnwrap(e["wrap"] as? Bool),
                pairs.map { CGPoint(x: $0[0], y: $0[1]) }
            )
        }
        return out
    }

    /// The test this file exists for. Swift reimplements where a vertex sits so
    /// a drag costs no round trip; if it disagrees with the engine, every
    /// vertex is drawn in slightly the wrong place and the lattice lies about
    /// which colours it is moving.
    func testEveryVertexSitsWhereTheEnginePutsIt() throws {
        for (name, entry) in try fixtureHomes() {
            let warp = WarpValue(
                cols: entry.cols, rows: entry.rows,
                offsets: Array(repeating: .zero, count: entry.cols * entry.rows)
            )
            let axes: WarpAxes = entry.wrap ? .hueSat : .chromaLuma
            let g = WarpGeometry(warp: warp, axes: axes, rect: plot())
            var i = 0
            for r in 0..<entry.rows {
                for c in 0..<entry.cols {
                    let got = g.home(col: c, row: r)
                    XCTAssertEqual(
                        got.x, entry.homes[i].x, accuracy: 0.0001,
                        "\(name) vertex (\(c),\(r)) u"
                    )
                    XCTAssertEqual(
                        got.y, entry.homes[i].y, accuracy: 0.0001,
                        "\(name) vertex (\(c),\(r)) v"
                    )
                    i += 1
                }
            }
        }
    }

    /// A wrapping axis has `cols` distinct positions around the ring and never
    /// reaches 1.0, because 1.0 is 0.0. An axis with ends reaches both.
    func testTheTwoAxisRulesAreActuallyDifferent() {
        let warp = WarpValue(cols: 6, rows: 4, offsets: Array(repeating: .zero, count: 24))
        let wrapped = WarpGeometry(warp: warp, axes: .hueSat, rect: plot())
        let clamped = WarpGeometry(warp: warp, axes: .chromaLuma, rect: plot())
        XCTAssertEqual(wrapped.home(col: 5, row: 0).x, 5.0 / 6.0, accuracy: 0.0001)
        XCTAssertEqual(clamped.home(col: 5, row: 0).x, 1.0, accuracy: 0.0001)
    }

    /// Screen and axis units have to be inverses, or a dragged vertex lands
    /// somewhere other than the pointer.
    func testTheTwoMappingsAreInverses() {
        let warp = WarpValue(cols: 6, rows: 6, offsets: Array(repeating: .zero, count: 36))
        for axes in [WarpAxes.hueSat, .chromaLuma] {
            let g = WarpGeometry(warp: warp, axes: axes, rect: plot())
            for at in [CGPoint(x: 0.25, y: 0.4), CGPoint(x: 0.6, y: 0.9), CGPoint(x: 0.1, y: 0.2)] {
                let back = g.fromScreen(g.toScreen(at))
                XCTAssertEqual(back.x, at.x, accuracy: 0.01, "\(axes) x")
                XCTAssertEqual(back.y, at.y, accuracy: 0.01, "\(axes) y")
            }
        }
    }

    /// Luma up, which is the way every other plot in the application draws it.
    func testTheRectangularPlotPutsLowLumaAtTheBottom() {
        let warp = WarpValue(cols: 2, rows: 2, offsets: Array(repeating: .zero, count: 4))
        let g = WarpGeometry(warp: warp, axes: .chromaLuma, rect: plot())
        XCTAssertEqual(g.toScreen(CGPoint(x: 0, y: 0)).y, 200, accuracy: 0.001)
        XCTAssertEqual(g.toScreen(CGPoint(x: 0, y: 1)).y, 0, accuracy: 0.001)
    }

    /// Hue zero is to the right and hue goes anticlockwise, matching the wheels.
    func testThePolarPlotPutsHueZeroToTheRight() {
        let warp = WarpValue(cols: 4, rows: 2, offsets: Array(repeating: .zero, count: 8))
        let g = WarpGeometry(warp: warp, axes: .hueSat, rect: plot())
        let outer = g.toScreen(CGPoint(x: 0, y: 1))
        XCTAssertGreaterThan(outer.x, 100, "hue zero should be right of centre")
        XCTAssertEqual(outer.y, 100, accuracy: 0.001, "and level with it")
        // A quarter turn is straight up, which in view coordinates is a
        // *smaller* y.
        let quarter = g.toScreen(CGPoint(x: 0.25, y: 1))
        XCTAssertEqual(quarter.x, 100, accuracy: 0.001)
        XCTAssertLessThan(quarter.y, 100)
    }

    func testAVertexIsOnlyGrabbedWhenItWasAimedAt() {
        let warp = WarpValue(cols: 6, rows: 6, offsets: Array(repeating: .zero, count: 36))
        let g = WarpGeometry(warp: warp, axes: .chromaLuma, rect: plot())
        let onIt = g.toScreen(g.home(col: 2, row: 3))
        let hit = g.nearest(to: onIt)
        XCTAssertEqual(hit?.col, 2)
        XCTAssertEqual(hit?.row, 3)
        // The middle of a cell is the only place genuinely far from every
        // vertex — on a six-column grid, a step to one side is most of the way
        // to the next vertex along.
        XCTAssertNil(g.nearest(to: CGPoint(x: onIt.x + 20, y: onIt.y + 20)))
    }

    /// A vertex is grabbed where it has been dragged to, not where it started.
    func testAMovedVertexIsGrabbedWhereItNowIs() {
        var offsets = [CGPoint](repeating: .zero, count: 36)
        offsets[3 * 6 + 2] = CGPoint(x: 0.15, y: 0.15)
        let warp = WarpValue(cols: 6, rows: 6, offsets: offsets)
        let g = WarpGeometry(warp: warp, axes: .chromaLuma, rect: plot())
        let moved = g.toScreen(CGPoint(x: g.home(col: 2, row: 3).x + 0.15,
                                       y: g.home(col: 2, row: 3).y + 0.15))
        XCTAssertEqual(g.nearest(to: moved)?.col, 2)
        XCTAssertEqual(g.nearest(to: moved)?.row, 3)
    }

    /// Dragging a red vertex a little anticlockwise must record a small
    /// negative offset, not almost a full turn the other way.
    func testAHueDragTakesTheShortWayRound() {
        let warp = WarpValue(cols: 6, rows: 2, offsets: Array(repeating: .zero, count: 12))
        let g = WarpGeometry(warp: warp, axes: .hueSat, rect: plot())
        // Vertex 0 sits at hue 0. Aim just below it — hue 0.97, which is a
        // twentieth of a turn *back*, not nineteen twentieths forward.
        let target = g.toScreen(CGPoint(x: 0.97, y: 0.5))
        let offset = g.offset(draggingCol: 0, row: 1, to: target)
        XCTAssertLessThan(offset.x, 0, "it went the long way round: \(offset.x)")
        XCTAssertGreaterThan(offset.x, -0.1)
    }

    func testADragIsClampedToWhatALatticeCanStore() {
        let warp = WarpValue(cols: 6, rows: 6, offsets: Array(repeating: .zero, count: 36))
        let g = WarpGeometry(warp: warp, axes: .chromaLuma, rect: plot())
        let far = g.offset(draggingCol: 0, row: 0, to: CGPoint(x: 9999, y: -9999))
        XCTAssertLessThanOrEqual(far.x, 0.5)
        XCTAssertLessThanOrEqual(far.y, 1.0)
        let back = g.offset(draggingCol: 5, row: 5, to: CGPoint(x: -9999, y: 9999))
        XCTAssertGreaterThanOrEqual(back.x, -0.5)
        XCTAssertGreaterThanOrEqual(back.y, -1.0)
    }

    func testAZeroSizedPlotDoesNotDivideByZero() {
        // SwiftUI lays out at zero size on the first pass, and a NaN there
        // propagates into the path and blanks the panel.
        let warp = WarpValue(cols: 2, rows: 2, offsets: Array(repeating: .zero, count: 4))
        for axes in [WarpAxes.hueSat, .chromaLuma] {
            let g = WarpGeometry(warp: warp, axes: axes, rect: .zero)
            let p = g.fromScreen(CGPoint(x: 5, y: 5))
            XCTAssertFalse(p.x.isNaN, "\(axes)")
            XCTAssertFalse(p.y.isNaN, "\(axes)")
        }
    }
}
