import Foundation

/// Swift's view of the Rust engine.
///
/// The *only* place in the Mac app that touches the C ABI. Everything above
/// this file works in Swift types and never sees a pointer, which is the same
/// firewall the Windows app has: the UI reads the stack, mutates a parameter,
/// asks for a texture, draws it. No image processing on this side of the line.
///
/// Scaffolded at M0 so the boundary exists and is exercised before the Mac port
/// actually starts. It compiles against `pe_ffi.h`, generated by
/// `build-engine.sh`.
enum Engine {
    /// Engine version, for the About panel and bug reports.
    static var version: String {
        guard let c = pe_version() else { return "unknown" }
        return String(cString: c)
    }
}

/// A document owned by the Rust engine.
///
/// A class, not a struct, so `deinit` reliably releases the Rust allocation.
/// Every handle handed across the boundary has exactly one owner on this side.
final class Document {
    private let handle: OpaquePointer

    /// Parse a document from JSON. Returns nil if the engine rejects it —
    /// malformed, or written by a newer schema version.
    init?(json: String) {
        guard let h = json.withCString({ pe_document_from_json($0) }) else {
            return nil
        }
        self.handle = OpaquePointer(h)
    }

    deinit {
        pe_document_free(UnsafeMutablePointer(handle))
    }

    /// Number of rows in the effect stack.
    var rowCount: Int {
        Int(pe_document_row_count(UnsafePointer(handle)))
    }

    /// Serialise back to JSON.
    ///
    /// Note the `defer`: the engine allocated this string, so the engine has to
    /// free it. Letting Swift's allocator near it would corrupt the heap.
    func toJSON() -> String? {
        guard let raw = pe_document_to_json(UnsafePointer(handle)) else {
            return nil
        }
        defer { pe_string_free(raw) }
        return String(cString: raw)
    }
}
