[package]
name = "pe-golden"
description = "Golden-image test harness"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
pe-color = { version = "0.0.1", path = "../../crates/pe-color" }
pe-io = { version = "0.0.1", path = "../../crates/pe-io" }
pe-render = { version = "0.0.1", path = "../../crates/pe-render" }

[dev-dependencies]
pe-core = { version = "0.0.1", path = "../../crates/pe-core" }
pe-effects = { version = "0.0.1", path = "../../crates/pe-effects" }
wgpu = "27"
