// Exposes the Rust engine's C ABI to Swift.
//
// pe_ffi.h is generated by apps/apple/build-engine.sh (via cbindgen) and is
// deliberately not committed, so it can never drift from crates/pe-ffi.
#import "pe_ffi.h"
